# -*- coding: utf-8 -*-
"""medico - classificador de gravidade de asma.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AxIvumX8e9TqeqD2CGVdjO3r7cE-tBPR
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# --- 1. VARIÁVEIS DE ENTRADA (ANTECEDENTES) ---

# Saturação de O2 (%)
saturacao = ctrl.Antecedent(np.arange(70, 101, 1), 'saturacao')
# Frequência Respiratória (resp/min)
fr = ctrl.Antecedent(np.arange(10, 51, 1), 'fr')
# Frequência Cardíaca (bpm)
fc = ctrl.Antecedent(np.arange(50, 151, 1), 'fc')

# --- 2. VARIÁVEL DE SAÍDA (CONSEQUENTE) ---

# Gravidade do Risco (Score 0-100)
gravidade = ctrl.Consequent(np.arange(0, 101, 1), 'gravidade')

print("Universos de Discurso (Ranges) definidos com sucesso.")

saturacao['baixa'] = fuzz.trapmf(saturacao.universe, [70, 70, 85, 88])
saturacao['media'] = fuzz.trimf(saturacao.universe, [85, 89, 93])
saturacao['alta'] = fuzz.trapmf(saturacao.universe, [91, 95, 100, 100])

fr['normal'] = fuzz.trimf(fr.universe, [10, 15, 20])
fr['alta'] = fuzz.trimf(fr.universe, [18, 28, 38])
fr['muito_alta'] = fuzz.trapmf(fr.universe, [30, 40, 50, 50])

fc['normal'] = fuzz.trimf(fc.universe, [50, 70, 90])
fc['elevada'] = fuzz.trimf(fc.universe, [80, 100, 120])
fc['taquicardia'] = fuzz.trapmf(fc.universe, [110, 130, 150, 150])

gravidade['leve'] = fuzz.trimf(gravidade.universe, [0, 15, 30])
gravidade['moderada'] = fuzz.trimf(gravidade.universe, [20, 40, 60])
gravidade['severa'] = fuzz.trimf(gravidade.universe, [50, 70, 85])
gravidade['risco_iminente'] = fuzz.trapmf(gravidade.universe, [75, 90, 100, 100])

print("Funções de Pertinência definidas. Visualização dos conjuntos fuzzy seria útil aqui.")
# Ex: saturacao.view()

# Regra 1: Melhor Cenário (Leve)
regra1 = ctrl.Rule(saturacao['alta'] & fc['normal'] & fr['normal'], gravidade['leve'])

# Regra 2: Crise Moderada
regra2 = ctrl.Rule(saturacao['media'] & fc['elevada'] & fr['alta'], gravidade['moderada'])

# Regra 3: Crise Severa (FC ou FR muito alta, mas SPO2 ainda média)
regra3 = ctrl.Rule(saturacao['media'] & (fc['taquicardia'] | fr['muito_alta']), gravidade['severa'])

# Regra 4: Risco Iminente (SPO2 Baixa é o principal driver)
regra4 = ctrl.Rule(saturacao['baixa'], gravidade['risco_iminente'])

# Regra 5: Risco Iminente (Combinação perigosa)
regra5 = ctrl.Rule(saturacao['baixa'] | fc['taquicardia'], gravidade['risco_iminente'])

# Regra 6: Severa (Estado entre moderada e risco)
regra6 = ctrl.Rule(saturacao['media'] & fc['taquicardia'], gravidade['severa'])

# --- Podemos adicionar mais regras para refinar o modelo, mas essas são as essenciais.
regras = [regra1, regra2, regra3, regra4, regra5, regra6]

print(f"Base de Conhecimento criada com {len(regras)} regras.")

# 1. Cria o sistema de controle com as regras
gravidade_ctrl = ctrl.ControlSystem(regras)

# 2. Cria a simulação para injetar inputs e obter o output
classificador_asma = ctrl.ControlSystemSimulation(gravidade_ctrl)

# A defuzzificação padrão (Centroid) será usada.
print("Sistema de Controle Fuzzy (SIF) construído com sucesso.")
# gravidade.view() # Visualização da saída

# Inputs: SPO2=90%, FR=25 resp/min, FC=105 bpm
classificador_asma.input['saturacao'] = 90
classificador_asma.input['fr'] = 25
classificador_asma.input['fc'] = 105

# Computa o resultado
classificador_asma.compute()
gravidade_moderada = classificador_asma.output['gravidade']

print("\n--- Cenário 1: Crise Moderada ---")
print(f"Resultado (Score de Gravidade): {gravidade_moderada:.2f}")

# Mapeando o score de volta para o termo linguístico
if gravidade_moderada <= 30:
    risco = "Leve"
elif gravidade_moderada <= 60:
    risco = "Moderada"
elif gravidade_moderada <= 85:
    risco = "Severa"
else:
    risco = "Risco Iminente"

print(f"Recomendação de Triagem: {risco}")
# O sistema deve recomendar 'Moderada' ou um score perto de 50.

# Inputs: SPO2=80%, FR=35 resp/min, FC=130 bpm
classificador_asma.input['saturacao'] = 80
classificador_asma.input['fr'] = 35
classificador_asma.input['fc'] = 130

# Computa o resultado
classificador_asma.compute()
gravidade_risco = classificador_asma.output['gravidade']

print("\n--- Cenário 2: Risco Iminente ---")
print(f"Resultado (Score de Gravidade): {gravidade_risco:.2f}")

# Mapeando o score de volta para o termo linguístico
if gravidade_risco <= 30:
    risco = "Leve"
elif gravidade_risco <= 60:
    risco = "Moderada"
elif gravidade_risco <= 85:
    risco = "Severa"
else:
    risco = "Risco Iminente"

print(f"Recomendação de Triagem: {risco}")
# O sistema deve recomendar 'Risco Iminente' ou um score perto de 90.

